### ISSUE TITLE
Error with Playlists

### ISSUE THREAD

**Issue by EvilEls** [oweitman/ioBroker.squeezeboxrpc#30]
Hi,
when I set `cmdPlayURL` to play m3u playlists, and after a while set `cmdPlayURL` to an arbitrary radio stream, the adapter crashes from time to time with this error and does not recover. 

```
squeezeboxrpc.0 | 2021-03-16 18:04:30.163 | error | (15531) TypeError: Cannot read property 'hasOwnProperty' of undefined     at ioSBPlayer.doPlayerUpdateStatus (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbplayer.js:539:28)     at IoSbSer
-- | -- | -- | --
squeezeboxrpc.0 | 2021-03-16 18:04:30.161 | error | (15531) uncaught exception: Cannot read property 'hasOwnProperty' of undefined
squeezeboxrpc.0 | 2021-03-16 18:04:25.693 | info | (15531) starting. Version 1.3.4 in /opt/iobroker/node_modules/iobroker.squeezeboxrpc, node: v12.21.0, js-controller: 3.2.16
squeezeboxrpc.0 | 2021-03-16 18:03:53.896 | warn | (2608) Terminated (UNCAUGHT_EXCEPTION): Without reason
squeezeboxrpc.0 | 2021-03-16 18:03:53.895 | info | (2608) terminating
squeezeboxrpc.0 | 2021-03-16 18:03:53.895 | info | (2608) squeezeboxrpc unloaded
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | (2608) Cannot read property 'hasOwnProperty' of undefined
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at endReadableNT (_stream_readable.js:1241:12)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at IncomingMessage.emit (events.js:326:22)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/jayson/lib/client/http.js:84:22)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at Object.Utils.JSON.parse (/opt/iobroker/node_modules/jayson/lib/utils.js:266:3)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at /opt/iobroker/node_modules/jayson/lib/client/index.js:140:10
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at ClientHttp.Client._parseResponse (/opt/iobroker/node_modules/jayson/lib/client/index.js:209:10)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at /opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:164:13
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at handle (/opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:62:13)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at IoSbServer.<anonymous> (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbserver.js:663:31)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | at ioSBPlayer.doPlayerUpdateStatus (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbplayer.js:539:28)
squeezeboxrpc.0 | 2021-03-16 18:03:53.884 | error | (2608) TypeError: Cannot read property 'hasOwnProperty' of undefined
squeezeboxrpc.0 | 2021-03-16 18:03:53.870 | error | (2608) uncaught exception: Cannot read property 'hasOwnProperty' of undefined

```

I have power down the player device and reboot to make the adapter work again.

Saw this on Boom and Radio.

Version 1.3.4 in /opt/iobroker/node_modules/iobroker.squeezeboxrpc, node: v12.21.0, js-controller: 3.2.16

**Comment by oweitman** [comment]
sorry for the delay.
i test this
first play a local m3u playlist
second i play a public shoutcast radiostream

i didnt get any problem
please can you retest this and if the problem persists can you please provide the url of the radiostream?
